version: '3'
services: 
  postgresql: 
    restart: always
    image: postgres
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  mongo:
    restart: always
    image: mongo
    ports:
      - 27017:27017
    entrypoint: 
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DB=${MONGO_DB}
        